# Generated by Django 4.2 on 2023-12-30 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Category',
            },
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_no', models.CharField(max_length=10)),
                ('cvv', models.CharField(max_length=3)),
                ('expiry', models.CharField(default='SOME STRING', max_length=7)),
                ('balance', models.FloatField(default=10000)),
            ],
            options={
                'db_table': 'payment',
            },
        ),
        migrations.CreateModel(
            name='Ice_creame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chillin_name', models.CharField(max_length=50)),
                ('price', models.FloatField(default=50)),
                ('description', models.CharField(max_length=100)),
                ('image', models.ImageField(default='abc.jpg', null=True, upload_to='image')),
                ('cate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.category')),
            ],
            options={
                'db_table': 'Ice_creame',
            },
        ),
    ]
