# Generated by Django 4.2 on 2023-12-31 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColdCoffee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cold_name', models.CharField(max_length=50)),
                ('cold_img', models.ImageField(default='abc.jpg', null=True, upload_to='cold_img')),
                ('receipe', models.CharField(max_length=1000)),
                ('price', models.FloatField(default=50)),
            ],
            options={
                'db_table': 'ColdCoffee',
            },
        ),
    ]
