# Generated by Django 4.2 on 2023-12-31 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_coldcoffee'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheeseCake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cheese_name', models.CharField(max_length=50)),
                ('cheese_img', models.ImageField(default='abc.jpg', null=True, upload_to='cheese_img')),
                ('receipe_cheese', models.CharField(max_length=1000)),
                ('cheese_price', models.FloatField(default=50)),
            ],
            options={
                'db_table': 'CheeseCake',
            },
        ),
        migrations.RenameField(
            model_name='coldcoffee',
            old_name='price',
            new_name='cold_price',
        ),
    ]
