# Generated by Django 4.2 on 2024-01-01 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_remove_mycart_cheese_cake_remove_mycart_cold_coffee'),
        ('backend', '0003_cheesecake_rename_price_coldcoffee_cold_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CheeseCake',
        ),
        migrations.DeleteModel(
            name='ColdCoffee',
        ),
    ]
