# Generated by Django 4.2 on 2024-01-03 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_remove_mycart_cheese_cake_remove_mycart_cold_coffee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=20)),
                ('l_name', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'Contact_info',
            },
        ),
    ]
